import '@/Global/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <link rel="shortcut icon" href="icon.ico" />
        {/* Other head elements */}
      </head>
      <body>
        {children}
        {metadata.title}
      </body>
    </html>
  );
}
